nname: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python & Kaggle
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Setup Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download CSV dataset
        run: |
          mkdir -p data
          kaggle datasets download -d prasad22/healthcare-dataset -p data --unzip

      - name: Run Docker Compose Migration
        working-directory: ${{ github.workspace }}
        run: docker compose up --build --abort-on-container-exit

      - name: Shut down Docker Compose
        working-directory: ${{ github.workspace }}
        if: always()
        run: docker compose down -v
