name: Test CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Kaggle
        run: pip install kaggle

      - name: Setup Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download CSV dataset
        run: |
          mkdir -p data
          kaggle datasets download -d prasad22/healthcare-dataset -p data --unzip

      - name: Run Docker Compose Migration
        run: docker compose up --build --abort-on-container-exit

      - name: Shut down Docker Compose
        if: always()
        run: docker compose down -v
