name: Data Migration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -R

      - name: Install Python & Kaggle
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      - name: Setup Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download CSV dataset
        run: |
          mkdir -p data
          kaggle datasets download -d prasad22/healthcare-dataset -p data --unzip

      - name: Run Docker Compose Migration
        run: |
          echo "Running Docker Compose from:"
          pwd
          docker compose -f ./docker-compose.yml up --build --abort-on-container-exit

      - name: Shut down Docker Compose
        if: always()
        run: docker compose -f ./docker-compose.yml down -v
