name: Test CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Display workspace
      - name: Display workspace
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE

      # 3️⃣ Install Python & Kaggle
      - name: Install Python & Kaggle
        run: |
          python -m pip install --upgrade pip
          pip install kaggle

      # 4️⃣ Setup Kaggle API
      - name: Setup Kaggle API
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"${KAGGLE_USERNAME}\",\"key\":\"${KAGGLE_KEY}\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # 5️⃣ Download CSV dataset from Kaggle
      - name: Download CSV dataset from Kaggle
        run: |
          mkdir -p data
          kaggle datasets download -d prasad22/healthcare-dataset -p data --unzip
          ls -la data

      # 6️⃣ Build and run Docker Compose
      - name: Build and run Docker Compose
       
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME}}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD}}
          MONGO_INITDB_DATABASE: ${{secrets.MONGO_DB}}
          MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME}}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD}}
          MONGO_DB: ${{secrets.MONGO_DB}}
          READER_USER: ${{ secrets.MONGO_USER1 }}
          READER_PASS: ${{ secrets.MONGO_PASSWORD1 }}
          MANAGER_USER: ${{ secrets.MONGO_USER2 }}
          MANAGER_PASS: ${{ secrets.MONGO_PASSWORD2 }}
          CSV_PATH:  ${{ secrets.CSV_PATH }}
          CSV_PATH_TEST: ${{secrets.CSV_PATH_TEST}}
          MONGO_DB_TEST: ${{secrets.MONGO_DB_TEST}}
          MONGO_COLLECTION_TEST: ${{secrets.MONGO_COLLECTION_TEST}}
        run: |
          docker compose -f Docker-compose.yml up --build --abort-on-container-exit

      # 7️⃣ Clean up
      - name: Clean up
        if: always()
        run: |
          docker compose -f Docker-compose.yml down -v
