name: Test Intégrité Projet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo_db:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          # Valeurs temporaires pour permettre le démarrage
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        options: >-
          --health-cmd "mongo --username root --password root --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download dataset
        run: |
          mkdir -p data
          python -c "import kagglehub; kagglehub.dataset_download('prasad22/healthcare-dataset', unzip=True, path='./data')"

      # Étape pour créer les utilisateurs réels avec les secrets
      - name: Initialize MongoDB users
        env:
          MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
          READER_USER: ${{ secrets.MONGO_USER1 }}
          READER_PASS: ${{ secrets.MONGO_PASSWORD1 }}
          MANAGER_USER: ${{ secrets.MONGO_USER2 }}
          MANAGER_PASS: ${{ secrets.MONGO_PASSWORD2 }}
          DB_NAME: ${{ secrets.MONGO_DATABASE }}
        run: |
          bash init-scripts/init-create-users.sh

      - name: Run migration script
        env:
          MONGO_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
        run: |
          python scripts/migrate_patients.py

      - name: Run tests
        run: |
          python -m unittest discover -s scripts -p "test_*.py"
