name: Test Intégrité Projet

on:
  push:
    branches:
      - workflow_test
  pull_request:
    branches:
      - workflow_test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo_db:
        image: mongo:7.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        options: >-
          --health-cmd "mongosh --host localhost -u root -p root --authenticationDatabase admin --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # 1️⃣ Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Installer les dépendances
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Télécharger le dataset public (via curl)
      - name: Download dataset
        run: |
          mkdir -p data
          curl -L -o data/healthcare_dataset.csv "https://www.kaggle.com/datasets/prasad22/healthcare-dataset/download?datasetVersionNumber=1"

      # 5️⃣ Initialiser les utilisateurs MongoDB
      - name: Initialize MongoDB users
        env:
          MONGO_HOST: mongo_db
          MONGO_PORT: 27017
          MONGO_ROOT_USERNAME: ${{secrets.MONGO_ROOT_USERNAME}}
          MONGO_ROOT_PASSWORD: ${{secrets.MONGO_ROOT_PASSWORD}}
          READER_USER: ${{secrets.MONGO_USER1}}
          READER_PASS: ${{secrets.MONGO_PASSWORD1}}
          MANAGER_USER: ${{secrets.MONGO_USER2}}
          MANAGER_PASS: ${{secrets.MONGO_PASSWORD2}}
          DB_NAME: ${{secrets.MONGO_DATABASE}}
        run: |
          bash init-scripts/init-create-users.sh

      # 6️⃣ Lancer le script de migration
      - name: Run migration script
        env:
          MONGO_ROOT_USERNAME: ${{secrets.MONGO_ROOT_USERNAME}}
          MONGO_ROOT_PASSWORD: ${{secrets.MONGO_ROOT_PASSWORD}}
        run: |
          python scripts/migrate_patients.py

      # 7️⃣ Lancer les tests
      - name: Run tests
        run: |
          python -m unittest discover -s scripts -p "test_*.py"

